server:
  port: 3306

spring:
  data:
    cassandra:
      keyspace-name: urlspace
      contact-points: 127.0.0.1
      port: 9042
      username: admin
      password: password
      local-datacenter: datacenter1
      schema-action: create_if_not_exists

  datasource:
    url: jdbc:h2:mem:mtd
    username: admin
    password: password

  h2:
    console:
      enabled: true

zookeeper:
  host: 127.0.0.1
  port: 2181
  counterDataPath: /counter
  range:
    limit: 10

